jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Start required service (e.g., Swagger PetStore API)
      run: |
        docker run -d -p 8080:8080 swaggerapi/petstore3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest
